services:
#  app:
#    build:
#      dockerfile: local.Dockerfile
#    restart: always
#    volumes:
#      - .:/app
#    ports:
#      - "1233:1234"
#    depends_on:
#      - redis
#      - db

  db:
    image: postgres:16.0
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    volumes:
      - data_postgresql:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - 6380:6379
    volumes:
      - data_redis:/data

volumes:
  data_postgresql:
  data_redis:
