services:
  app:
    build:
      dockerfile: local.Dockerfile
    container_name: auth-telegram-container
    volumes:
      - .:/app
    restart: always
    ports:
      - "1234:1234"
    networks:
      - pg
      - redis
      - allapps

networks:
  pg:
    name: pg
    external: true
  redis:
    name: redis
    external: true
  allapps:
    name: allapps
    external: true
