definitions:
  dto.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  dto.ResendCodeResponse:
    properties:
      message:
        type: string
    type: object
  dto.TokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      login:
        type: string
      name:
        type: string
      surname:
        type: string
      updated_at:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.SignInData:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  model.SignUpData:
    properties:
      login:
        type: string
      password:
        type: string
      telegram:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/refresh-tokens:
    post:
      consumes:
      - application/json
      description: Generates new access and refresh tokens using a provided refresh
        token
      parameters:
      - description: Refresh Token Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens generated successfully
          schema:
            $ref: '#/definitions/dto.TokensResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Generate new access and refresh tokens
      tags:
      - Auth
  /auth/resend-code:
    post:
      consumes:
      - application/json
      description: Resend a verification code to the user based on the provided sign-up
        data
      parameters:
      - description: Sign-up data required to resend the code
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SignUpData'
      produces:
      - application/json
      responses:
        "200":
          description: Message with link to complete registration
          schema:
            $ref: '#/definitions/dto.ResendCodeResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Resend verification code
      tags:
      - Auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Authenticate a user with the provided sign-in data
      parameters:
      - description: Sign-in data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SignInData'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully signed in, no content
          schema:
            type: nil
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Failed to sign in
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: User Sign In
      tags:
      - Auth
  /user/info:
    get:
      consumes:
      - application/json
      description: Получение информации о пользователе по его UUID
      parameters:
      - description: User ID (UUID)
        in: header
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get user information
      tags:
      - users
swagger: "2.0"
